version: '3.7'
services: 
    mysql-server:
        image: mysql:latest
        restart: always
        container_name: mysql-server
        ports: 
            - 3306:3306
        volumes:
            - mysql-server:/var/lib/mysql
            - ./db-init/:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes: 
    mysql-server:
        name: mysql-data